[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "contracts/test"
cache_path = "cache"

# Solidity compiler settings
solc_version = "0.8.21"
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing
verbosity = 3
fuzz_runs = 256

# Formatting
line_length = 100
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
local = "http://127.0.0.1:8545"


